---
# role tasks
- name: sat_firewall | Install firewalld
  become: "{{ firewalld_become }}"
  package:
    name: firewalld
    state: present

- name: sat_firewall | enable and start firewalld
  become: "{{ firewalld_become }}"
  service:
    name: firewalld
    state: started
    enabled: true

- name: sat_firewall | open ports for zone "{{ firewalld_zone }}" (IPv4+IPv6)
  become: "{{ firewalld_become }}"
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    zone: "{{ firewalld_zone }}"
  loop: "{{ firewalld_ports_open }}"

- name: sat_firewall | add services for zone "{{ firewalld_zone }}"
  become: "{{ firewalld_become }}"
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    zone: "{{ firewalld_zone }}"
  loop: "{{ firewalld_services }}"

#- name: sat_firewall | locally forward ports for zone "{{ firewalld_zone }}" (IPv4+IPv6)
#  become: "{{ firewalld_become }}"
#  firewalld:
#    rich_rule: >
#      rule family="{{ item[0] }}" forward-port port="{{ item[1].port }}"
#      protocol="{{ item[1].proto }}" to-port="{{ item[1].to_port }}"
#    state: enabled
#    permanent: true
#    immediate: true
#    zone: "{{ firewalld_zone }}"
#  loop: "{{ lookup('nested', [ 'ipv4', 'ipv6' ], firewalld_ports_forward) }}"
